// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkyAq5DbbPTKIcvh5dmY7QZMONFNogonc',
    appId: '1:693513486039:web:c4edab6e9f483b98857a92',
    messagingSenderId: '693513486039',
    projectId: 'tiktok-clone-lee',
    authDomain: 'tiktok-clone-lee.firebaseapp.com',
    storageBucket: 'tiktok-clone-lee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsLZdz7DsV_5DRvTofFxKFYkN9W8yZtuw',
    appId: '1:693513486039:android:a3cb6d4e410c3e1f857a92',
    messagingSenderId: '693513486039',
    projectId: 'tiktok-clone-lee',
    storageBucket: 'tiktok-clone-lee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbC0SWm0F0IPy0kZh-eby_DNEG3LQQ2-g',
    appId: '1:693513486039:ios:c5b4d68e2b3ab0a0857a92',
    messagingSenderId: '693513486039',
    projectId: 'tiktok-clone-lee',
    storageBucket: 'tiktok-clone-lee.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkyAq5DbbPTKIcvh5dmY7QZMONFNogonc',
    appId: '1:693513486039:web:dd3d0edcfa521049857a92',
    messagingSenderId: '693513486039',
    projectId: 'tiktok-clone-lee',
    authDomain: 'tiktok-clone-lee.firebaseapp.com',
    storageBucket: 'tiktok-clone-lee.firebasestorage.app',
  );

}